version: '3'
services:
  memcached:
    image: memcached
    container_name: 'memcached'
    ports: 
      - "11211:11211"
  client:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_client
    container_name: 'client-python'
    working_dir: '/root/opt'
    depends_on: 
      - memcached
    tty: true
    volumes:
      - .\client:/root/opt
